id: P010790
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:24:38.732984
source_metadata:
  id: bdr:W6458
  title: ཡ་མཚན་སྤྲུལ་པའི་གླེགས་བམ
  author: ''
  volumes:
    6699bef56f9e46499e9be750a90d4129:
      image_group_id: I1724
      title: ''
      volume_number: 7
      total_pages: 179
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
